[program:smm-schedule]
command=php /var/www/smm_server/artisan schedule:work
directory=/var/www/smm_server
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/smm-schedule.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
