[program:welike-worker-order-place-add-priority]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/smm_server/artisan order_place:order add-priority
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/smm_server/storage/order-place-add-priority.log
stderr_logfile=/var/www/smm_server/storage/order-place-add-priority-error.log
stopwaitsecs=120
