[program:welike-worker-resell-order-add-priority]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/smm_server/artisan resell:order add-priority
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/smm_server/storage/resell-order-add-priority.log
stderr_logfile=/var/www/smm_server/storage/resell-order-add-priority-error.log
stopwaitsecs=120
